//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSavePositionSample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,500,400")]
        public global::System.Windows.Rect MainWindow_Bounds {
            get {
                return ((global::System.Windows.Rect)(this["MainWindow_Bounds"]));
            }
            set {
                this["MainWindow_Bounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfColumnSetting xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance""
xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
<ColumnSetting>
<DisplayIndex>0</DisplayIndex>
<Width>-1</Width>
</ColumnSetting>
<ColumnSetting>
<DisplayIndex>1</DisplayIndex>
<Width>-1</Width>
</ColumnSetting>
<ColumnSetting>
<DisplayIndex>2</DisplayIndex>
<Width>-1</Width>
</ColumnSetting>
<ColumnSetting>
<DisplayIndex>3</DisplayIndex>
<Width>-1</Width>
</ColumnSetting>
</ArrayOfColumnSetting>")]
        public System.Collections.Generic.List<ColumnSetting> DataGrid_Columns {
            get {
                return ((System.Collections.Generic.List<ColumnSetting>)(this["DataGrid_Columns"]));
            }
            set {
                this["DataGrid_Columns"] = value;
            }
        }
    }
}
